### ISSUE TITLE
[Android] Compilation failed; see the compiler error output for details.

### ISSUE THREAD

**Issue by saranathishara** [WhatsApp/stickers#469]
After Upgrade to 3.4 Android Version with distributionUrl=https\://services.gradle.org/distributions/gradle-5.1.1-all.zip

error: cannot access AnimatedImage
class file for com.facebook.imagepipeline.animated.base.AnimatedImage not found

**Comment by simonzhexu** [comment]
will take a look. thanks.

**Comment by simonzhexu** [comment]
fixed in f4952c8bedb825ffb7d7eb057cf835ca2ba4118b

**Comment by saranathishara** [comment]
Great Job. Thank You. :)
